/**
 * Auto-update engine for the Synthetix desktop app (Windows-first).
 *
 * DESIGN CONTEXT — why this is hand-rolled, not electron-updater:
 * The real app payload (~1.4GB: CPython + ONNX model + .next + node_modules +
 * workers) ships via electron-builder `extraResources` to resources/app/, NOT
 * in app.asar. electron-updater's default behavior only replaces app.asar
 * (~30KB main JS here), so it would be a no-op on the real app. We therefore
 * fetch our own `latest.json` manifest, stream-download the chosen asset, and
 * delegate the actual install to a platform applier (win-full-applier /
 * win-patch-applier). This keeps the heavy extraResources payload in scope.
 *
 * Two update paths (see docs/auto-update-design-2026-07-08.md §3):
 *   - "full"  : download NSIS installer → silent reinstall (always available)
 *   - "patch" : download content zip → replace .next/ + public/ in place
 *               (Phase 3; not yet wired — applyWinPatch is injected later)
 *
 * The manifest and status types here are the single contract shared with the
 * renderer via preload IPC and src/lib/update-bridge.ts.
 */
import { app } from "electron";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import https from "https";
import { URL } from "url";
import { computeRuntimeHash } from "./runtime-hash";
import { verifyManifest } from "./manifest-signing";
import { appRoot } from "./paths";
// The Ed25519 public key baked into the app at build time (generated by
// scripts/generate-signing-key.mjs → electron/generated/update-pubkey.ts). Used
// to verify every fetched manifest before it's trusted (Plan A supply-chain
// guard). Lives under electron/ so the main-process tsconfig compiles it.
import { updatePubkey } from "./generated/update-pubkey";

// ─── public types (mirrored on the renderer side via preload) ───────────────

/** Identifier for the current runtime platform + arch. */
export type Platform = "win-x64" | "darwin-arm64" | "darwin-x64";

/** Which install path the engine has resolved for an available update. */
export type UpdatePath = "patch" | "full";

export type UpdateStatus =
  /** No check has run yet (initial state before first check completes). */
  | { kind: "idle" }
  /** A check is in flight (manifest being fetched). */
  | { kind: "checking" }
  /** Running version >= latest known version. */
  | { kind: "up-to-date"; latestVersion: string; checkedAt: string }
  /** A newer version is available and the user can choose to install it. */
  | {
      kind: "available";
      path: UpdatePath;
      version: string;
      releaseName?: string;
      sizeBytes: number;
      /** Localized release notes keyed by locale tag; renderer picks by locale. */
      releaseNotes?: Record<string, string>;
      /** Whether skipping is blocked (current < minRequiredVersion). */
      forced: boolean;
    }
  /** Download in progress. `path` retained so the UI label stays consistent. */
  | { kind: "downloading"; path: UpdatePath; version: string; progress: number; downloadedBytes: number; totalBytes: number }
  /** Asset downloaded + verified; the applier runs on downloadAndInstall(). */
  | { kind: "ready"; path: UpdatePath; version: string; stagedPath: string }
  /** Applying the update (next server stopped, installer running, etc.). */
  | { kind: "installing"; path: UpdatePath; version: string }
  | { kind: "error"; message: string };

// ─── manifest types (shape of latest.json) ──────────────────────────────────

interface ManifestAssetFull {
  url: string;
  size: number;
  sha256: string;
  /** Authenticode signature value, once code signing is wired (Phase 3). */
  signature?: string;
}
interface ManifestAssetPatch {
  availableFrom: string[];
  url: string;
  size: number;
  sha256: string;
  includesMigrations: boolean;
  /** Runtime-layer fingerprint guard; mismatch forces a downgrade to "full". */
  minRuntimeHash?: string;
}
interface ManifestPlatform {
  /** Publisher's declared update kind. The engine still re-evaluates it. */
  updateKind?: "patch" | "full";
  full: ManifestAssetFull;
  patch?: ManifestAssetPatch;
}
interface LatestManifest {
  version: string;
  releaseName?: string;
  channel: string;
  publishedAt?: string;
  /** Versions below this MUST update; the UI blocks dismissal. */
  minRequiredVersion?: string;
  releaseNotes?: Record<string, string>;
  /** Force full even if a patch is available (e.g. emergency rollback). */
  forceFull?: boolean;
  platforms: Partial<Record<Platform, ManifestPlatform>>;
}

// ─── config ─────────────────────────────────────────────────────────────────

/**
 * Where to fetch the update manifest. Override at runtime with the
 * SYNTHETIX_UPDATE_URL env var (e.g. for a beta channel or self-hosted mirror).
 * Default points at a fixed-name asset published to GitHub Releases so the
 * release script only has to upload one file per channel.
 */
function manifestUrl(): string {
  const override = process.env.SYNTHETIX_UPDATE_URL;
  if (override) return override;
  const channel = (process.env.SYNTHETIX_UPDATE_CHANNEL ?? "stable").toLowerCase();
  return `https://github.com/WalkCloud/Synthetix/releases/download/latest/${channel}.json`;
}

/** The platform key the engine selects assets for. */
export function currentPlatform(): Platform {
  const p = process.platform;
  const a = process.arch;
  if (p === "win32" && a === "x64") return "win-x64";
  if (p === "darwin" && a === "arm64") return "darwin-arm64";
  if (p === "darwin" && a === "x64") return "darwin-x64";
  // Fallback — keep Windows as the only currently-supported target.
  return "win-x64";
}

// ─── semver-lite (no dependency; only what we need) ─────────────────────────

/** Parse "1.2.3-pre+build" → [1, 2, 3]. Pre-release/build ignored for compare. */
function parseSemver(v: string): [number, number, number] | null {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec((v || "").trim());
  if (!m) return null;
  return [Number(m[1]), Number(m[2]), Number(m[3])];
}

/**
 * Returns 1 if a > b, -1 if a < b, 0 if equal. Pre-release tags are ignored
 * (treated as the release they point at). Unparseable versions sort below
 * parseable ones, so a bogus remote version never forces an "update".
 */
export function compareVersions(a: string, b: string): number {
  const pa = parseSemver(a);
  const pb = parseSemver(b);
  if (!pa && !pb) return 0;
  if (!pa) return -1;
  if (!pb) return 1;
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pa[i] < pb[i] ? -1 : 1;
  }
  return 0;
}

// ─── HTTP helpers ───────────────────────────────────────────────────────────

/** Fetch a URL as UTF-8 text with a timeout. Follows redirects (up to 5). */
function fetchText(url: string, timeoutMs = 15_000): Promise<string> {
  return new Promise((resolve, reject) => {
    let hops = 0;
    const get = (target: string) => {
      let parsed: URL;
      try {
        parsed = new URL(target);
      } catch (e) {
        reject(new Error(`invalid url: ${target}`));
        return;
      }
      const req = https.get(
        {
          hostname: parsed.hostname,
          path: parsed.pathname + parsed.search,
          port: parsed.port || 443,
          headers: { "User-Agent": `Synthetix/${app.getVersion()} (updater)` },
          timeout: timeoutMs,
        },
        (res) => {
          // Follow redirects.
          if (
            (res.statusCode === 301 || res.statusCode === 302 || res.statusCode === 303 ||
              res.statusCode === 307 || res.statusCode === 308) &&
            res.headers.location &&
            hops < 5
          ) {
            hops += 1;
            res.resume();
            const next = new URL(res.headers.location, target).toString();
            get(next);
            return;
          }
          if (res.statusCode !== 200) {
            res.resume();
            reject(new Error(`manifest fetch failed: HTTP ${res.statusCode}`));
            return;
          }
          const chunks: Buffer[] = [];
          res.on("data", (c: Buffer) => chunks.push(c));
          res.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
          res.on("error", reject);
        }
      );
      req.on("timeout", () => {
        req.destroy(new Error("manifest fetch timed out"));
      });
      req.on("error", reject);
    };
    get(url);
  });
}

interface DownloadResult {
  filePath: string;
  bytes: number;
}

/**
 * Stream-download `url` to `destPath`, verifying the SHA-256 against
 * `expectedSha256`. `onProgress(received, total)` fires during the transfer
 * (total is 0 if the server omits Content-Length). Aborts cleanly when the
 * AbortController passed in `signal` is triggered.
 */
function downloadFile(
  url: string,
  destPath: string,
  expectedSha256: string,
  onProgress: (received: number, total: number) => void,
  signal?: AbortSignal
): Promise<DownloadResult> {
  return new Promise((resolve, reject) => {
    let hops = 0;
    const hash = crypto.createHash("sha256");
    let received = 0;
    let total = 0;
    let stream: fs.WriteStream | null = null;
    let settled = false;

    const cleanup = () => {
      try { stream?.close(); } catch { /* ignore */ }
    };
    const fail = (err: Error) => {
      if (settled) return;
      settled = true;
      cleanup();
      try { fs.unlinkSync(destPath); } catch { /* ignore */ }
      reject(err);
    };
    const ok = (result: DownloadResult) => {
      if (settled) return;
      settled = true;
      resolve(result);
    };

    if (signal) {
      signal.addEventListener(
        "abort",
        () => fail(new Error("download aborted")),
        { once: true }
      );
    }

    const get = (target: string) => {
      let parsed: URL;
      try {
        parsed = new URL(target);
      } catch (e) {
        fail(new Error(`invalid download url: ${target}`));
        return;
      }
      const req = https.get(
        {
          hostname: parsed.hostname,
          path: parsed.pathname + parsed.search,
          port: parsed.port || 443,
          headers: { "User-Agent": `Synthetix/${app.getVersion()} (updater)` },
        },
        (res) => {
          if (
            (res.statusCode === 301 || res.statusCode === 302 || res.statusCode === 303 ||
              res.statusCode === 307 || res.statusCode === 308) &&
            res.headers.location &&
            hops < 5
          ) {
            hops += 1;
            res.resume();
            get(new URL(res.headers.location, target).toString());
            return;
          }
          if (res.statusCode !== 200) {
            res.resume();
            fail(new Error(`download failed: HTTP ${res.statusCode}`));
            return;
          }
          total = Number(res.headers["content-length"] || 0);
          stream = fs.createWriteStream(destPath);
          res.on("data", (c: Buffer) => {
            received += c.length;
            hash.update(c);
            stream?.write(c);
            onProgress(received, total);
          });
          res.on("end", () => {
            stream?.end(() => {
              const actual = hash.digest("hex").toLowerCase();
              if (actual !== expectedSha256.toLowerCase()) {
                fail(
                  new Error(
                    `sha256 mismatch: expected ${expectedSha256.slice(0, 12)}…, got ${actual.slice(0, 12)}…`
                  )
                );
                return;
              }
              ok({ filePath: destPath, bytes: received });
            });
          });
          res.on("error", fail);
        }
      );
      req.on("error", fail);
    };
    get(url);
  });
}

// ─── staging dir ────────────────────────────────────────────────────────────

function stagingDir(): string {
  const dir = path.join(app.getPath("userData"), "update-staging");
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

// ─── applier injection ──────────────────────────────────────────────────────

/**
 * An applier performs the platform-specific install of a verified, staged
 * update asset. The updater engine stays platform-agnostic; main.ts wires the
 * concrete appliers (win-full-applier, and later win-patch-applier).
 */
export type Applier = (
  stagedPath: string,
  version: string,
  pathKind: UpdatePath,
  onInstalling: () => void
) => Promise<void>;

const appliers: Partial<Record<UpdatePath, Applier>> = {};

/** Register the concrete installer for a path kind (called from main.ts). */
export function registerApplier(pathKind: UpdatePath, fn: Applier): void {
  appliers[pathKind] = fn;
}

// ─── status + event fan-out ─────────────────────────────────────────────────

type Listener = (status: UpdateStatus) => void;
const listeners = new Set<Listener>();
let currentStatus: UpdateStatus = { kind: "idle" };

/** Subscribe to status changes. Returns an unsubscribe function. */
export function onStatus(listener: Listener): () => void {
  listeners.add(listener);
  // Replay current status immediately so a late subscriber doesn't miss it.
  listener(currentStatus);
  return () => {
    listeners.delete(listener);
  };
}

export function getStatus(): UpdateStatus {
  return currentStatus;
}

function setStatus(next: UpdateStatus): void {
  currentStatus = next;
  for (const l of listeners) {
    try {
      l(next);
    } catch {
      /* a bad listener must not break the engine */
    }
  }
}

// ─── check + download + install ─────────────────────────────────────────────

let downloadAbort: AbortController | null = null;

/**
 * Fetch the manifest and recompute the status. Safe to call repeatedly; does
 * not start a download. Sets status to up-to-date / available / error.
 */
export async function checkForUpdates(): Promise<UpdateStatus> {
  // Don't clobber a running download/install with a re-check.
  if (currentStatus.kind === "downloading" || currentStatus.kind === "installing") {
    return currentStatus;
  }
  setStatus({ kind: "checking" });
  try {
    const raw = await fetchText(manifestUrl());

    // Verify the manifest signature (Plan A supply-chain guard) BEFORE trusting
    // any field in it. verifyManifest also parses the JSON and returns the
    // signable subset; we widen it back to the full LatestManifest shape after.
    const verified = verifyManifest(raw, updatePubkey);
    if (!verified.ok) {
      // Signature present but INVALID → refuse to update. This is the tamper-
      // detection path: a MITMed or replaced manifest cannot ship code.
      throw new Error(`manifest rejected: ${verified.reason}`);
    }
    if (verified.unsigned) {
      // No signature field. Allowed during the transition period; tighten to
      // reject once every published release carries a signature.
      console.warn("[updater] manifest is UNSIGNED — accepting (transition mode)");
    }
    if (!verified.manifest) {
      throw new Error("manifest parsed but contained no signable content");
    }

    // Re-parse for the full (richer) type — verifyManifest only returns the
    // security-critical subset. The signature already pinned the asset fields,
    // so we trust the rest (releaseNotes, timestamps) as non-security metadata.
    let manifest: LatestManifest;
    try {
      manifest = JSON.parse(raw) as LatestManifest;
    } catch (e) {
      throw new Error("manifest is not valid JSON");
    }
    const platformKey = currentPlatform();
    const platformBlock = manifest.platforms[platformKey];
    if (!platformBlock) {
      throw new Error(`manifest has no asset for platform ${platformKey}`);
    }
    const currentVer = app.getVersion();
    const latestVer = manifest.version;

    if (compareVersions(latestVer, currentVer) <= 0) {
      const status: UpdateStatus = {
        kind: "up-to-date",
        latestVersion: latestVer,
        checkedAt: new Date().toISOString(),
      };
      setStatus(status);
      return status;
    }

    const forced = manifest.minRequiredVersion
      ? compareVersions(currentVer, manifest.minRequiredVersion) < 0
      : false;

    // Resolve the update path. Patch is only eligible when the manifest
    // declares it, forceFull is not set, the running version is in the patch's
    // availableFrom list, AND the local runtime-layer hash matches the
    // manifest's minRuntimeHash. A runtime-layer mismatch (e.g. the publisher
    // mis-tagged a runtime change as a patch, or the user's install drifted)
    // silently downgrades to full so we never try to overlay a JS-only content
    // zip on top of a changed native/runtime layer.
    let resolvedPath: UpdatePath = "full";
    if (!manifest.forceFull && platformBlock.patch) {
      const fromList = platformBlock.patch.availableFrom ?? [];
      const eligible = fromList.some((v) => compareVersions(v, currentVer) === 0);
      if (eligible && platformBlock.updateKind !== "full") {
        if (platformBlock.patch.minRuntimeHash) {
          const localHash = computeRuntimeHash(appRoot());
          if (localHash !== platformBlock.patch.minRuntimeHash) {
            console.log(
              "[updater] runtime-hash mismatch — downgrading patch to full"
            );
          } else {
            resolvedPath = "patch";
          }
        } else {
          // No hash declared — trust the publisher's availableFrom list.
          resolvedPath = "patch";
        }
      }
    }
    // If no full asset exists and we fell back to "full", that's a publish
    // error — surface it instead of silently showing an un-clickable update.
    if (resolvedPath === "full" && !platformBlock.full) {
      throw new Error(`manifest for ${latestVer} has no full asset for ${platformKey}`);
    }
    if (resolvedPath === "patch" && !platformBlock.patch) {
      resolvedPath = "full";
    }

    const asset = resolvedPath === "patch" ? platformBlock.patch! : platformBlock.full;
    const status: UpdateStatus = {
      kind: "available",
      path: resolvedPath,
      version: latestVer,
      releaseName: manifest.releaseName,
      sizeBytes: asset.size,
      releaseNotes: manifest.releaseNotes,
      forced,
    };
    setStatus(status);
    return status;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const status: UpdateStatus = { kind: "error", message };
    setStatus(status);
    return status;
  }
}

/**
 * Download the asset of the currently-available update, verify it, and leave
 * it staged. Does not install — call applyStagedUpdate() (or let the user
 * confirm first). If a status is already "ready", this is a no-op.
 */
export async function downloadUpdate(): Promise<UpdateStatus> {
  if (currentStatus.kind !== "available") {
    return currentStatus;
  }
  const { path: pathKind, version, sizeBytes } = currentStatus;
  const platformKey = currentPlatform();
  // Re-fetch manifest to get the asset URL — we don't cache it long-term, and
  // this keeps a single source of truth for url/sha256.
  let manifest: LatestManifest;
  try {
    manifest = JSON.parse(await fetchText(manifestUrl())) as LatestManifest;
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    setStatus({ kind: "error", message: `failed to resolve download: ${message}` });
    return currentStatus;
  }
  const block = manifest.platforms[platformKey];
  if (!block) {
    setStatus({ kind: "error", message: `no platform block for ${platformKey}` });
    return currentStatus;
  }
  const asset = pathKind === "patch" ? block.patch : block.full;
  if (!asset) {
    setStatus({ kind: "error", message: `no ${pathKind} asset on manifest` });
    return currentStatus;
  }

  const ext = pathKind === "patch" ? "zip" : "exe";
  const destPath = path.join(stagingDir(), `synthetix-${version}-${pathKind}.${ext}`);
  downloadAbort = new AbortController();
  setStatus({
    kind: "downloading",
    path: pathKind,
    version,
    progress: 0,
    downloadedBytes: 0,
    totalBytes: sizeBytes,
  });
  try {
    await downloadFile(
      asset.url,
      destPath,
      asset.sha256,
      (received, total) => {
        const progress = total > 0 ? received / total : 0;
        setStatus({
          kind: "downloading",
          path: pathKind,
          version,
          progress,
          downloadedBytes: received,
          totalBytes: total || sizeBytes,
        });
      },
      downloadAbort.signal
    );
    const status: UpdateStatus = {
      kind: "ready",
      path: pathKind,
      version,
      stagedPath: destPath,
    };
    setStatus(status);
    return status;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    setStatus({ kind: "error", message: `download failed: ${message}` });
    return currentStatus;
  } finally {
    downloadAbort = null;
  }
}

/**
 * Apply a staged update. Requires status "ready". Dispatches to the applier
 * registered for the path kind. The applier is responsible for the actual
 * reinstall / file replacement and (for full) quitting the app so the
 * installer can take over.
 */
export async function applyStagedUpdate(): Promise<void> {
  if (currentStatus.kind !== "ready") {
    return;
  }
  const { path: pathKind, version, stagedPath } = currentStatus;
  const applier = appliers[pathKind];
  if (!applier) {
    setStatus({ kind: "error", message: `no applier registered for path "${pathKind}"` });
    return;
  }
  setStatus({ kind: "installing", path: pathKind, version });
  try {
    await applier(stagedPath, version, pathKind, () => {
      // installing status already set; applier can call this as a hook if it
      // needs to do additional synchronous work before quitting.
    });
    // For "patch" the app stays alive and the status will be reset by the
    // caller after the next-server restarts. For "full", the applier quits
    // the app and this line is never reached.
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    setStatus({ kind: "error", message: `install failed: ${message}` });
  }
}

/** Convenience: download then immediately apply (the "立即更新" button). */
export async function downloadAndInstall(): Promise<void> {
  const after = await downloadUpdate();
  if (after.kind === "ready") {
    await applyStagedUpdate();
  }
}

/** Cancel any in-flight download. No-op if not downloading. */
export function cancelDownload(): void {
  if (downloadAbort) {
    downloadAbort.abort();
  }
}
